package com.example.speccyose5ultrav021b

object Translator {
    
    private val strings = mapOf(
        "es_ES" to mapOf(
            "SYS_SETTINGS" to "AJUSTES",
            "SYS_IA" to "IA ARCHITECT",
            "SYS_APPS" to "APPS",
            "SYS_HARDWARE" to "NÚCLEO",
            "SYS_DEVICE" to "DISPOSITIVO",
            "DEVICE_SELECT_DESC" to "Cambia el perfil de hardware si el detectado es incorrecto.",
            "FAVORITES" to "FAVORITOS",
            "RECENT" to "RECIENTES",
            "SYNCING" to "SINCRONIZANDO...",
            "PRESS_A" to "PULSA [A] PARA ENTRAR",
            "ROMS" to "ROMS",
            "HOURS_PLAYED" to "HORAS JUEGO",
            "LAST_GAME" to "ÚLTIMO JUEGO",
            "NONE" to "NINGUNO",
            "NO_MEDIA" to "NO MEDIA",
            "SETTINGS_CORE" to "Configuración de librerías, audio, temas y red neuronal.",
            "SETTINGS_IA" to "Inteligencia Artificial integrada para soporte y tácticas.",
            "SETTINGS_APPS" to "Acceso directo a aplicaciones nativas del dispositivo.",
            "SETTINGS_HW" to "Gestión térmica, perfiles de CPU y overclocking.",
            "TELEMETRY_TITLE" to "NÚCLEO IMPERIAL",
            "LIBRARY_TITLE" to "BIBLIOTECA NEURAL",
            "ENERGY_PROFILES" to "PERFILES DE ENERGÍA",
            "CLOUD_SAVE" to "CLOUD SAVE IMPERIAL",
            "NEURAL_LINK" to "ENLACE NEURAL",
            "SYSTEM_ONLINE" to "SISTEMA ONLINE",
            "BACK_HUB" to "VOLVER ATRÁS",
            "LAUNCH" to "LANZAR",
            "CLOSE_PANEL" to "CERRAR PANEL"
        ),
        "en_US" to mapOf(
            "SYS_SETTINGS" to "SETTINGS",
            "SYS_IA" to "IA ARCHITECT",
            "SYS_APPS" to "APPS",
            "SYS_HARDWARE" to "CORE",
            "SYS_DEVICE" to "DEVICE",
            "DEVICE_SELECT_DESC" to "Change hardware profile if detection was wrong.",
            "FAVORITES" to "FAVORITES",
            "RECENT" to "RECENT",
            "SYNCING" to "SYNCING...",
            "PRESS_A" to "PRESS [A] TO ENTER",
            "ROMS" to "ROMS",
            "HOURS_PLAYED" to "HOURS PLAYED",
            "LAST_GAME" to "LAST PLAYED",
            "NONE" to "NONE",
            "NO_MEDIA" to "NO MEDIA",
            "SETTINGS_CORE" to "Library, audio, themes and neural net configuration.",
            "SETTINGS_IA" to "Integrated AI for support and tactical data.",
            "SETTINGS_APPS" to "Direct access to native device applications.",
            "SETTINGS_HW" to "Thermal management, CPU profiles and overclocking.",
            "TELEMETRY_TITLE" to "IMPERIAL CORE",
            "LIBRARY_TITLE" to "NEURAL LIBRARY",
            "ENERGY_PROFILES" to "ENERGY PROFILES",
            "CLOUD_SAVE" to "IMPERIAL CLOUD SAVE",
            "NEURAL_LINK" to "NEURAL LINK",
            "SYSTEM_ONLINE" to "SYSTEM ONLINE",
            "BACK_HUB" to "GO BACK",
            "LAUNCH" to "LAUNCH",
            "CLOSE_PANEL" to "CLOSE PANEL"
        ),
        "fr_FR" to mapOf(
            "SYS_SETTINGS" to "PARAMÈTRES",
            "SYS_IA" to "IA ARCHITECTE",
            "SYS_APPS" to "APPLICATIONS",
            "SYS_HARDWARE" to "NOYAU",
            "SYS_DEVICE" to "APPAREIL",
            "FAVORITES" to "FAVORIS",
            "RECENT" to "RÉCENTS",
            "SYNCING" to "SYNCHRONISATION...",
            "PRESS_A" to "APPUYEZ SUR [A]",
            "ROMS" to "ROMS",
            "HOURS_PLAYED" to "HEURES DE JEU",
            "LAST_GAME" to "DERNIER JEU",
            "NONE" to "AUCUN",
            "NO_MEDIA" to "SANS MÉDIA",
            "SETTINGS_CORE" to "Configuration des bibliothèques, audio et thèmes.",
            "SETTINGS_IA" to "IA intégrée pour le support et la tactique.",
            "SETTINGS_APPS" to "Accès direct aux applications natives.",
            "SETTINGS_HW" to "Gestion thermique et profils CPU.",
            "TELEMETRY_TITLE" to "NOYAU IMPÉRIAL",
            "LIBRARY_TITLE" to "BIBLIOTHÈQUE NEURALE",
            "ENERGY_PROFILES" to "PROFILS D'ÉNERGIE",
            "CLOUD_SAVE" to "SAUVEGARDE CLOUD",
            "NEURAL_LINK" to "LIEN NEURAL",
            "SYSTEM_ONLINE" to "SYSTÈME EN LIGNE",
            "BACK_HUB" to "RETOUR",
            "LAUNCH" to "LANCER",
            "CLOSE_PANEL" to "FERMER LE PANNEAU"
        ),
        "pt_BR" to mapOf(
            "SYS_SETTINGS" to "AJUSTES",
            "SYS_IA" to "IA ARCHITECT",
            "SYS_APPS" to "APPS",
            "SYS_HARDWARE" to "NÚCLEO",
            "SYS_DEVICE" to "DISPOSITIVO",
            "FAVORITES" to "FAVORITOS",
            "RECENT" to "RECENTES",
            "SYNCING" to "SINCRONIZANDO...",
            "PRESS_A" to "PRESSIONE [A]",
            "ROMS" to "ROMS",
            "HOURS_PLAYED" to "HORAS JOGADAS",
            "LAST_GAME" to "ÚLTIMO JOGO",
            "NONE" to "NENHUM",
            "NO_MEDIA" to "SEM MÍDIA",
            "SETTINGS_CORE" to "Configuração de bibliotecas, áudio e temas.",
            "SETTINGS_IA" to "IA integrada para suporte e táticas.",
            "SETTINGS_APPS" to "Acesso a aplicativos nativos.",
            "SETTINGS_HW" to "Gerenciamento térmico e perfis de CPU.",
            "TELEMETRY_TITLE" to "NÚCLEO IMPERIAL",
            "LIBRARY_TITLE" to "BIBLIOTECA NEURAL",
            "ENERGY_PROFILES" to "PERFIS DE ENERGIA",
            "CLOUD_SAVE" to "CLOUD SAVE IMPERIAL",
            "LINK NEURAL" to "LINK NEURAL",
            "SYSTEM_ONLINE" to "SISTEMA ONLINE",
            "BACK_HUB" to "VOLTAR",
            "LAUNCH" to "INICIAR",
            "CLOSE_PANEL" to "FECHAR PAINEL"
        ),
        "zh_CN" to mapOf(
            "SYS_SETTINGS" to "设置",
            "SYS_IA" to "架构师人工智能",
            "SYS_APPS" to "应用",
            "SYS_HARDWARE" to "核心",
            "SYS_DEVICE" to "设备",
            "FAVORITES" to "收藏",
            "RECENT" to "最近",
            "SYNCING" to "同步中...",
            "PRESS_A" to "按 [A] 进入",
            "ROMS" to "游戏",
            "HOURS_PLAYED" to "游玩时间",
            "LAST_GAME" to "最后运行",
            "NONE" to "无",
            "NO_MEDIA" to "无媒体",
            "SETTINGS_CORE" to "库、音频、主题 and 神经网配置。",
            "SETTINGS_IA" to "集成人工智能支持和战术 data。",
            "SETTINGS_APPS" to "直接访问原生设备应用程序。",
            "SETTINGS_HW" to "散热管理、CPU 配置文件和超频。",
            "TELEMETRY_TITLE" to "帝国核心",
            "LIBRARY_TITLE" to "神经图书馆",
            "ENERGY_PROFILES" to "性能模式",
            "CLOUD_SAVE" to "帝国云存档",
            "NEURAL_LINK" to "神经连接",
            "SYSTEM_ONLINE" to "系统在线",
            "BACK_HUB" to "返回",
            "LAUNCH" to "启动",
            "CLOSE_PANEL" to "关闭面板"
        ),
        "ja_JP" to mapOf(
            "SYS_SETTINGS" to "設定",
            "SYS_IA" to "アーキテクトAI",
            "SYS_APPS" to "アプリ",
            "SYS_HARDWARE" to "コア",
            "SYS_DEVICE" to "デバイス",
            "FAVORITES" to "お気に入り",
            "RECENT" to "履歴",
            "SYNCING" to "同期中...",
            "PRESS_A" to "[A] ボタンで決定",
            "ROMS" to "ゲーム",
            "HOURS_PLAYED" to "プレイ時間",
            "LAST_GAME" to "最終プレイ",
            "NONE" to "なし",
            "NO_MEDIA" to "メディアなし",
            "SETTINGS_CORE" to "ライブラリ、オーディオ、テーマ、ニューラルネットワークの設定。",
            "SETTINGS_IA" to "サポートと戦術データのための統合AI。",
            "SETTINGS_APPS" to "デバイスのネイティブアプリへの直接アクセス。",
            "SETTINGS_HW" to "熱管理、CPUプロファイル、オーバークロック。",
            "TELEMETRY_TITLE" to "帝国コア",
            "LIBRARY_TITLE" to "ニューラルライブラリ",
            "ENERGY_PROFILES" to "電力プロファイル",
            "CLOUD_SAVE" to "帝国クラウドセーブ",
            "NEURAL_LINK" to "ニューラルリンク",
            "SYSTEM_ONLINE" to "システムオンライン",
            "BACK_HUB" to "戻る",
            "LAUNCH" to "起動",
            "CLOSE_PANEL" to "パネルを閉じる"
        )
    )

    fun getString(lang: String, key: String): String {
        val languageDict = strings[lang] ?: strings["en_US"] ?: return key
        return languageDict[key] ?: strings["en_US"]?.get(key) ?: key
    }
}
